config/routes.rb
Rails.application.routes.draw do

  resources :route_state_associations
  resources :route_plane_associations
  post "periods/change", as: :change_periods


  resources :machine_period_associations
  resources :periods
  resources :product_period_associations
  resources :product_product_associations
  resources :machines
  resources :items
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  resources :translinks
  resources :demandsites
  resources :supplysites
  resources :sites
  resources :products
  resources :states
  resources :planes
  resources :routes


  get 'transport_start', to: 'static_pages#transport_start'
  get 'mlclsp_start', to: 'static_pages#mlclsp_start'
  get 'aircraft_start', to: 'static_pages#aircraft_start'

  post 'translinks/read_and_show_ofv', :to => 'translinks#read_and_show_ofv'
  post 'translinks/read_transportation_quantities', :to => 'translinks#read_transportation_quantities'
  post 'translinks/optimize', :to => 'translinks#optimize'
  post 'translinks/delete_transportation_quantities', :to => 'translinks#delete_transportation_quantities'

  post 'product_periods/read_and_show_ofv', :to => 'product_period_associations#read_and_show_ofv'
  post 'product_periods/read_optimization_results', :to => 'product_period_associations#read_optimization_results'
  post 'product_periods/optimize', :to => 'product_period_associations#optimize'
  post 'product_periods/delete_old_plan', :to => 'product_period_associations#delete_old_plan'
  post 'product_periods/show_index_page', :to => 'product_period_associations#show_index_page'

  post 'route_planes/read_and_show_ofv', :to => 'route_plane_associations#read_and_show_ofv'
  post 'route_planes/read_optimization_results', :to => 'route_plane_associations#read_optimization_results'
  post 'route_states/read_and_show_passengers', :to => 'route_state_associations#read_and_show_passengers'
  post 'route_planes/optimize', :to => 'route_plane_associations#optimize'
  post 'route_planes/delete_old_plan', :to => 'route_plane_associations#delete_old_plan'
  post 'route_planes/show_index_page', :to => 'route_plane_associations#show_index_page'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The Website "Operations Management Application" is a collection of user interfaces to access different optimization models.
</p>

app/views/static_pages/aircraft_start.html.erb
<% provide(:title, 'Aircraft Allocation Model') %>
<h1>Aircraft Allocation Model</h1>
<p>
<p>
<div class="line-back">
  <p>
    <strong>You can start the aircraft allocation model on this page!</strong>
  </p>
</div>
<strong>1. Step:</strong> Enter or edit the basic data for the aircraft optimization model. <br>
These inputs are needed before you can enter the associations between routes, demand states and aircraft types.<br>
<strong>
  <br>
  <div class="photo-row">
    <div class="photo"><%= link_to "Edit Routes", routes_path %><br><br><%= link_to image_tag("route_.png", :width => 70, :height => 70, :title => "Edit routes"), routes_path %></div><div class="photo"><%= link_to "Edit aircraft types", planes_path %><br><br><%= link_to image_tag("airc.jpg", :width => 70, :height => 70, :title => "Edit aircraft types"), planes_path %></div><div class="photo"><%= link_to "Edit demand states", states_path %><br><br><%= link_to image_tag("szenario.jpg", :width => 70, :height => 70, :title => "Edit demand states"), states_path %></div>
  </div>
  <br>
  <br>
</strong>
<strong>2. Step:</strong> Enter the informations for the association between routes/aircraft types and routes/demand states.<br><br>
<strong>
  <div class="photo-row-2">
    <div class="photo"><%= link_to "Edit aircraft type characteristics for routes", route_plane_associations_path %><br><br><%= link_to image_tag("aircroute.jpg", :width => 70, :height => 70, :title => "Edit aircraft type characteristics for routes"), route_plane_associations_path %></div><div class="photo"><%= link_to "Edit demand states for routes", route_state_associations_path %><br><br><%= link_to image_tag("demand.jpg", :width => 70, :height => 70, :title => "Edit demand states for routes"), route_state_associations_path %></div>
  </div>
</strong>
</p>
<% if logged_in? %>
    <p>
    <div class="line-back">
      <p>
        <strong>After updating your data we can run the optimization model!</strong>
      </p>
    </div>
    <strong>3. Step:</strong> Run the optimization model and acces the results.<br><br>
    <strong><%= button_to "Delete old data and run optimization model", :controller => 'route_plane_associations', :action => 'optimize' %></strong>
    <strong>NOTE:</strong> The results will also be saved as EXCEL-file in the aircraft_app folder.<br><br>
    <strong><%= button_to "Upload and show planes assigned for routes", :controller => 'route_plane_associations', :action => 'read_optimization_results' %>
      <%= button_to "Upload and show passengers carried and bumped for demand states", :controller => 'route_state_associations', :action => 'read_and_show_passengers' %>
      <%= button_to "Upload and show calculated total costs", :controller => 'route_plane_associations', :action => 'read_and_show_ofv' %></strong>

    </p>


<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact for support on the Operations Management Apps:<br></br>

  <b>jochenbebermeier@web.de</b><br>or</br><b>jonas.brune@web.de</b>


</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Contact for support on the Operations Management Apps:<br></br>

  <b>jochenbebermeier@web.de</b><br>or</br><b>jonas.brune@web.de</b>
  <br><br>


  <strong>Useful Literature:</strong><br><br>

  Operations Management Tutorial (2014), Stefan Helber



</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="stats">
          <%= render 'shared/stats' %>
        </section>
        <section class="micropost_form">
          <%= render 'shared/micropost_form' %>
        </section>
      </aside>
      <div class="col-md-8">
        <h3>Micropost Feed</h3>
        <%= render 'shared/feed' %>
      </div>
    </div>
<% else %>

    <div class="center jumbotron">
      <h1><strong>Welcome to the Operations Management Application</strong></h1>

      <br>

      <h2>
        This is the home page for the Operations Management Application created for the class "Development of operational application systems" <br>
        of the Operations Management and Research Major
      </h2>

      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>

<!--    <%= link_to image_tag("rails.png", alt: "Rails logo"),
                'http://rubyonrails.org/' %>-->
<% end %>

app/views/static_pages/mlclsp_start.html.erb
<% provide(:title, 'Losgrößenplanung') %>
<h1>Mehrstufige Losgrößenplanung mit dem MLCLSP</h1>
<p>
Auf dieser Seite startet die Losgrößenplanung!    <br>     <br>

  <%= link_to "Hier geht es zur Verwaltung der Produkte!", products_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Machinen!", machines_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Perioden!", periods_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Produkte-Produkte-Relationen!", product_product_associations_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Produkte-Perioden-Relationen!", product_period_associations_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Maschinen-Perioden-Relationen!", machine_period_associations_path %><br>
</p>

<br>


<% if logged_in? %>

    <p>

      Nach der Eingabe der Daten können wir nun endlich optimieren!

      <%= button_to "Lösche den Produktions- und Lagerplan", :controller => 'product_period_associations', :action => 'delete_old_plan' %>
      <%= button_to "Optimiere", :controller => 'product_period_associations', :action => 'optimize' %>
      <%= button_to "Lies die Ergebnisse ein", :controller => 'product_period_associations', :action => 'read_optimization_results' %>
      <%= button_to "Lies den Zielfunktionswert ein", :controller => 'product_period_associations', :action => 'read_and_show_ofv' %>

    </p>

<% end %>

app/views/static_pages/transport_start.html.erb
<% provide(:title, 'Transportplanung') %>
<h1>Klassisches Transportmodell</h1>
<p>
Auf dieser Seite startet die Transportplanung!    <br>     <br>

<%= link_to "Hier geht es zur Verwaltung der Orte!", sites_path %><br>
<%= link_to "Hier geht es zur Verwaltung der Angebotsdaten!", supplysites_path %><br>
<%= link_to "Hier geht es zur Verwaltung der Nachfragedaten!", demandsites_path %><br>
<%= link_to "Hier geht es zur Verwaltung der Transportrelationen!", translinks_path %><br>
</p>

<br>


<% if logged_in? %>





<p>

Nach der Eingabe der Daten können wir nun endlich optimieren!

  <%= button_to "Lösche Transportmengen", :controller => 'translinks', :action =>  'delete_transportation_quantities'  %>
  <%= button_to "Optimiere", :controller => 'translinks', :action =>  'optimize'  %>
  <%= button_to "Lies die Transportmengen ein", :controller => 'translinks', :action =>  'read_transportation_quantities'  %>
  <%= button_to "Lies den Zielfunktionswert ein", :controller => 'translinks', :action =>  'read_and_show_ofv'  %>

</p>

<% end %>