config/routes.rb
Rails.application.routes.draw do

  resources :route_state_associations
  resources :route_plane_associations
  post "periods/change", as: :change_periods


  resources :machine_period_associations
  resources :periods
  resources :product_period_associations
  resources :product_product_associations
  resources :machines
  resources :items
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  resources :translinks
  resources :demandsites
  resources :supplysites
  resources :sites
  resources :products
  resources :states
  resources :planes
  resources :routes


  get 'transport_start', to: 'static_pages#transport_start'
  get 'mlclsp_start', to: 'static_pages#mlclsp_start'
  get 'aircraft_start', to: 'static_pages#aircraft_start'

  post 'translinks/read_and_show_ofv', :to => 'translinks#read_and_show_ofv'
  post 'translinks/read_transportation_quantities', :to => 'translinks#read_transportation_quantities'
  post 'translinks/optimize', :to => 'translinks#optimize'
  post 'translinks/delete_transportation_quantities', :to => 'translinks#delete_transportation_quantities'

  post 'product_periods/read_and_show_ofv', :to => 'product_period_associations#read_and_show_ofv'
  post 'product_periods/read_optimization_results', :to => 'product_period_associations#read_optimization_results'
  post 'product_periods/optimize', :to => 'product_period_associations#optimize'
  post 'product_periods/delete_old_plan', :to => 'product_period_associations#delete_old_plan'
  post 'product_periods/show_index_page', :to => 'product_period_associations#show_index_page'

  post 'route_planes/read_and_show_ofv', :to => 'route_plane_associations#read_and_show_ofv'
  post 'route_planes/read_optimization_results', :to => 'route_plane_associations#read_optimization_results'
  post 'route_states/read_and_show_passengers', :to => 'route_state_associations#read_and_show_passengers'
  post 'route_planes/optimize', :to => 'route_plane_associations#optimize'
  post 'route_planes/delete_old_plan', :to => 'route_plane_associations#delete_old_plan'
  post 'route_planes/show_index_page', :to => 'route_plane_associations#show_index_page'

end

app/models/translink.rb
# == Schema Information
#
# Table name: translinks
#
#  id                 :integer          not null, primary key
#  supplysite_id      :integer
#  demandsite_id      :integer
#  unit_cost          :float
#  transport_quantity :float
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Translink < ActiveRecord::Base
#  attr_accessible :demandsite_id, :supplysite_id, :transport_quantity, :unit_cost
  validates :transport_quantity, :numericality => { :greater_than_or_equal_to => 0}
  validates :unit_cost, :numericality => { :greater_than_or_equal_to => 0}

  belongs_to :supplysite
  belongs_to :demandsite
end

app/controllers/translinks_controller.rb
class TranslinksController < ApplicationController
  before_filter :logged_in_user

  # GET /translinks
  # GET /translinks.json
  def index
    @translinks = Translink.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @translinks }
    end
  end

  # GET /translinks/1
  # GET /translinks/1.json
  def show
    @translink = Translink.find(params[:id])
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @translink }
    end
  end

  # GET /translinks/new
  # GET /translinks/new.json
  def new
    @translink = Translink.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @translink }
    end
  end

  # GET /translinks/1/edit
  def edit
    @translink = Translink.find(params[:id])
  end

  # POST /translinks
  # POST /translinks.json
  def create
    @translink = Translink.new(translink_params)

    @translink.transport_quantity=0.0


    respond_to do |format|
      if @translink.save
        format.html { redirect_to @translink, notice: 'Transportrelation wurde erfolgreich angelegt.' }
        format.json { render json: @translink, status: :created, location: @translink }
      else
        format.html { render action: "new" }
        format.json { render json: @translink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /translinks/1
  # PUT /translinks/1.json
  def update
    @translink = Translink.find(params[:id])

#    if params[:translink][:transport_quantity]=nil
#        params[:translink][:transport_quantity]=0.0
#    end

#    @translink = Translink.new(params[:translink])
#        if @translink.transport_quantity=nil
#          @translink.transport_quantity=0.0
#        end

#    @translink.transport_quantity=0

    respond_to do |format|
      if @translink.update_attributes(translink_params)
        format.html { redirect_to @translink, notice: 'Transportrelation wurde erfolgreich aktualisiert.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @translink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translinks/1
  # DELETE /translinks/1.json
  def destroy
    @translink = Translink.find(params[:id])
    @translink.destroy

    respond_to do |format|
      format.html { redirect_to translinks_url }
      format.json { head :no_content }
    end
  end


  def optimize

    if File.exist?("Transportmodell_v3_Input_Instanz1.inc")
      File.delete("Transportmodell_v3_Input_Instanz1.inc")
    end
    f=File.new("Transportmodell_v3_Input_Instanz1.inc", "w")
    printf(f, "set i / \n")
    @supplysites = Supplysite.all
    @supplysites.each { |ssi| printf(f, "i" + ssi.id.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "j / \n")
    @demandsites = Demandsite.all
    @demandsites.each { |dsi| printf(f, "j" + dsi.id.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "l / \n")
    @translinks = Translink.all
    @translinks.each { |li| printf(f, "l" + li.id.to_s + "\n") }
    printf(f, "/;" + "\n\n")


    printf(f, "LI(l,i) = no;\n")
    printf(f, "LJ(l,j) = no;\n\n")

    @translinks.each do |li|
      printf(f, "LI( 'l" + li.id.to_s + "', 'i" + li.supplysite_id.to_s + "') = yes;\n")
      printf(f, "LJ( 'l" + li.id.to_s + "', 'j" + li.demandsite_id.to_s + "') = yes;\n\n")
    end
    printf(f, "\n\n")

    printf(f, "Parameter\n  A(i) /\n")

    @supplysites.each { |so| printf(f, "i" + so.id.to_s + "  " + so.supply_quantity.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "\nN(j) /\n")

    @demandsites.each { |si| printf(f, "j" + si.id.to_s + "  " + si.demand_quantity.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "\nc(l) /\n")

    @translinks.each { |li| printf(f, "l" + li.id.to_s + "  " + li.unit_cost.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, ";\n")
    f.close


    if File.exist?("Transportmengen_v2.txt")
      File.delete("Transportmengen_v2.txt")
    end

    system "C:\\GAMS\\win64\\24.5\\gams Transportmodell_v2"

#    @translinks = Translink.all
    flash.now[:started] = "Die Rechnung wurde gestartet!"
    render 'static_pages/transport_start'

  end


  def read_transportation_quantities

    if File.exist?("Transportmengen_v2.txt")

      fi=File.open("Transportmengen_v2.txt", "r")
      fi.each { |line| # printf(f,line)
        sa=line.split(";")
        sa0=sa[0].delete "l "
        sa3=sa[3].delete " \n"
        al=Translink.find_by_id(sa0)
        al.transport_quantity=sa3
        al.save

      }
      fi.close
      @translinks = Translink.all
      render :template => "translinks/index"
    else
      flash.now[:not_available] = "Transportmengen wurden noch nicht berechnet!"
      @translinks = Translink.all
      render :template => "translinks/index"
    end


  end


  def delete_transportation_quantities

    if File.exist?("Transportmengen_v2.txt")
      File.delete("Transportmengen_v2.txt")
    end
    if File.exist?("Zielfunktionswert_v2.txt")
      File.delete("Zielfunktionswert_v2.txt")
    end

    @translinks = Translink.all
    @translinks.each { |li|
#      li.transport_quantity=0.0
      li.transport_quantity=nil
      li.save
    }

    @objective_function_value=nil

    render :template => "translinks/index"

  end

  def read_and_show_ofv

    if File.exist?("Zielfunktionswert_v2.txt")
      fi=File.open("Zielfunktionswert_v2.txt", "r")
      line=fi.readline
      fi.close
      sa=line.split(" ")
      @objective_function_value=sa[1]
    else
      @objective_function_value=nil
      flash.now[:not_available] = "Zielfunktionswert wurde noch nicht berechnet!"

    end

    @translinks = Translink.all
    render :template => "translinks/index"
  end


end





private

  def logged_in_user
    unless logged_in?
      store_location
      redirect_to signin_path, notice: "Bitte melden Sie sich an."
    end
  end

  def translink_params
    params.require(:translink).permit(:demandsite_id, :supplysite_id, :transport_quantity, :unit_cost)
  end

app/helpers/translinks_helper.rb
module TranslinksHelper
end

app/views/translinks/_form.html.erb
<%= form_for(@translink) do |f| %>
  <% if @translink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translink.errors.count, "error") %> prohibited this translink from being saved:</h2>

      <ul>
      <% @translink.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Angebotsort' %><br />
    <%= f.collection_select :supplysite_id, Supplysite.all, :id, :supplysite_codename %>

  </div>
  <div class="field">
    <%= f.label 'Nachfrageort' %><br />
    <%= f.collection_select :demandsite_id, Demandsite.all, :id, :demandsite_codename %>
  </div>
  <div class="field">
    <%= f.label 'Einheitskostensatz' %><br />
    <%= f.text_field :unit_cost %>
  </div>
  <div class="actions">
    <%= f.submit'Transportrelation anlegen oder aktualisieren' %>
  </div>
<% end %>

app/views/translinks/edit.html.erb
<h1>Transportrelationen ändern</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @translink %> |
<%= link_to 'Zurück', translinks_path %>

app/views/translinks/index.html.erb
<h1>Übersicht der Transportrelationen</h1>

<table class="table">
  <tr>
    <th>Angebotsort</th>
    <th>Nachfrageort</th>
    <th>Einheitstransportkostensatz</th>
    <th>Ermittelte Transportmenge</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @translinks.each do |translink| %>
  <tr>
    <td><%= translink.supplysite.site.codename %></td>
    <td><%= translink.demandsite.site.codename %></td>
    <td><%= translink.unit_cost %></td>
    <td><%= translink.transport_quantity %></td>
    <td><%= link_to 'Ändern', edit_translink_path(translink) %></td>
    <td><%= link_to 'Löschen', translink, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
  </tr>
<% end %>
</table>

<br />



<br />

<% if @objective_function_value!=nil %>
    Die Kosten betragen <%=   @objective_function_value %> Geldeinheiten!   <br>   <br>
<% end %>

<%= link_to 'Neue Transportrelation', new_translink_path %>


<br>  <br>
<%= link_to 'Zurück zur Transportplanung', transport_start_path %>

app/views/translinks/new.html.erb
<h1>Neue Transportrelation</h1>

<%= render 'form' %>

<%= link_to 'Zurück', translinks_path %>

app/views/translinks/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <b>Angebotsort</b>
  <%= @translink.supplysite_id %>
</p>

<p>
  <b>Nachfrageort</b>
  <%= @translink.demandsite_id %>
</p>

<p>
  <b>Einheitstransportkostensatz</b>
  <%= @translink.unit_cost %>
</p>

<p>
  <b>Transportmenge</b>
  <%= @translink.transport_quantity %>
</p>


<%= link_to 'Ändern', edit_translink_path(@translink) %> |
<%= link_to 'Zurück', translinks_path %>