config/routes.rb
Rails.application.routes.draw do

  resources :route_state_associations
  resources :route_plane_associations
  post "periods/change", as: :change_periods


  resources :machine_period_associations
  resources :periods
  resources :product_period_associations
  resources :product_product_associations
  resources :machines
  resources :items
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  resources :translinks
  resources :demandsites
  resources :supplysites
  resources :sites
  resources :products
  resources :states
  resources :planes
  resources :routes


  get 'transport_start', to: 'static_pages#transport_start'
  get 'mlclsp_start', to: 'static_pages#mlclsp_start'
  get 'aircraft_start', to: 'static_pages#aircraft_start'

  post 'translinks/read_and_show_ofv', :to => 'translinks#read_and_show_ofv'
  post 'translinks/read_transportation_quantities', :to => 'translinks#read_transportation_quantities'
  post 'translinks/optimize', :to => 'translinks#optimize'
  post 'translinks/delete_transportation_quantities', :to => 'translinks#delete_transportation_quantities'

  post 'product_periods/read_and_show_ofv', :to => 'product_period_associations#read_and_show_ofv'
  post 'product_periods/read_optimization_results', :to => 'product_period_associations#read_optimization_results'
  post 'product_periods/optimize', :to => 'product_period_associations#optimize'
  post 'product_periods/delete_old_plan', :to => 'product_period_associations#delete_old_plan'
  post 'product_periods/show_index_page', :to => 'product_period_associations#show_index_page'

  post 'route_planes/read_and_show_ofv', :to => 'route_plane_associations#read_and_show_ofv'
  post 'route_planes/read_optimization_results', :to => 'route_plane_associations#read_optimization_results'
  post 'route_states/read_and_show_passengers', :to => 'route_state_associations#read_and_show_passengers'
  post 'route_planes/optimize', :to => 'route_plane_associations#optimize'
  post 'route_planes/delete_old_plan', :to => 'route_plane_associations#delete_old_plan'
  post 'route_planes/show_index_page', :to => 'route_plane_associations#show_index_page'

end

app/models/supplysite.rb
# == Schema Information
#
# Table name: supplysites
#
#  id              :integer          not null, primary key
#  site_id         :integer
#  supply_quantity :float
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Supplysite < ActiveRecord::Base
#  attr_accessible :supply_quantity, :site_id
  validates :supply_quantity, :numericality => { :greater_than => 0}


  belongs_to :site
  has_many :translinks, :dependent => :destroy
  accepts_nested_attributes_for :translinks


  def supplysite_codename
    self.site.codename
  end
end

app/controllers/supplysites_controller.rb
class SupplysitesController < ApplicationController

  before_filter :logged_in_user


  # GET /supplysites
  # GET /supplysites.json
  def index
    @supplysites = Supplysite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @supplysites }
    end
  end

  # GET /supplysites/1
  # GET /supplysites/1.json
  def show
    @supplysite = Supplysite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @supplysite }
    end
  end

  # GET /supplysites/new
  # GET /supplysites/new.json
  def new
    @supplysite = Supplysite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @supplysite }
    end
  end

  # GET /supplysites/1/edit
  def edit
    @supplysite = Supplysite.find(params[:id])
  end

  # POST /supplysites
  # POST /supplysites.json
  def create
    @supplysite = Supplysite.new(supplysite_params)

    respond_to do |format|
      if @supplysite.save
        format.html { redirect_to @supplysite, notice: 'Angebotsort wurde erfolgreich angelegt.' }
        format.json { render json: @supplysite, status: :created, location: @supplysite }
      else
        format.html { render action: "new" }
        format.json { render json: @supplysite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /supplysites/1
  # PUT /supplysites/1.json
  def update
    @supplysite = Supplysite.find(params[:id])

    respond_to do |format|
      if @supplysite.update_attributes(supplysite_params)
        format.html { redirect_to @supplysite, notice: 'Angebotsort wurde erfolgreich aktualisiert.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @supplysite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplysites/1
  # DELETE /supplysites/1.json
  def destroy
    @supplysite = Supplysite.find(params[:id])
    @supplysite.destroy

    respond_to do |format|
      format.html { redirect_to supplysites_url }
      format.json { head :no_content }
    end
  end
end


private

  def logged_in_user
    unless logged_in?
      store_location
      redirect_to signin_path, notice: "Bitte melden Sie sich an."
    end
  end

  def supplysite_params
    params.require(:supplysite).permit(:supply_quantity, :site_id)
  end

app/helpers/supplysites_helper.rb
module SupplysitesHelper
end

app/views/supplysites/_form.html.erb
<%= form_for(@supplysite) do |f| %>
  <% if @supplysite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supplysite.errors.count, "error") %> prohibited this supplysite from being saved:</h2>

      <ul>
      <% @supplysite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Code auswählen' %><br />
    <%= f.collection_select :site_id, Site.all, :id, :codename %>
  </div>
  <div class="field">
    <%= f.label 'Angebotsmenge eingeben' %><br />
    <%= f.text_field :supply_quantity %>
  </div>
  <div class="actions">
    <%= f.submit "Angebotsort anlegen oder aktualisieren" %>
  </div>
<% end %>

app/views/supplysites/edit.html.erb
<h1>Angebotsort ändern</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @supplysite %> |
<%= link_to 'Zurück', supplysites_path %>

app/views/supplysites/index.html.erb
<h1>Daten der Angebotsorte</h1>

<table class="table">
  <tr>
    <th>Code</th>
    <th>Ort</th>
    <th>Angebotsmenge</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @supplysites.each do |supplysite| %>
  <tr>
    <td><%= supplysite.site.codename %></td>
    <td><%= supplysite.site.name %></td>
    <td><%= supplysite.supply_quantity %></td>
    <td><%= link_to 'Ändern', edit_supplysite_path(supplysite) %></td>
    <td><%= link_to 'Löschen', supplysite, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Neuen Angebotsort anlegen', new_supplysite_path %><br>  <br>
<%= link_to 'Zurück zur Transportplanung', transport_start_path %>

app/views/supplysites/new.html.erb
<h1>Neuer Angebotsort</h1>

<%= render 'form' %>

<%= link_to 'Zurück', supplysites_path %>

app/views/supplysites/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<p>
  <b>Angebotsort:</b>
  <%= @supplysite.site.name %>
</p>

<p>
  <b>Angebotsmenge:</b>
  <%= @supplysite.supply_quantity %>
</p>


<%= link_to 'Ändern', edit_supplysite_path(@supplysite) %> |
<%= link_to 'Zurück', supplysites_path %>