config/routes.rb
Rails.application.routes.draw do

  resources :route_state_associations
  resources :route_plane_associations
  post "periods/change", as: :change_periods


  resources :machine_period_associations
  resources :periods
  resources :product_period_associations
  resources :product_product_associations
  resources :machines
  resources :items
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  resources :translinks
  resources :demandsites
  resources :supplysites
  resources :sites
  resources :products
  resources :states
  resources :planes
  resources :routes


  get 'transport_start', to: 'static_pages#transport_start'
  get 'mlclsp_start', to: 'static_pages#mlclsp_start'
  get 'aircraft_start', to: 'static_pages#aircraft_start'

  post 'translinks/read_and_show_ofv', :to => 'translinks#read_and_show_ofv'
  post 'translinks/read_transportation_quantities', :to => 'translinks#read_transportation_quantities'
  post 'translinks/optimize', :to => 'translinks#optimize'
  post 'translinks/delete_transportation_quantities', :to => 'translinks#delete_transportation_quantities'

  post 'product_periods/read_and_show_ofv', :to => 'product_period_associations#read_and_show_ofv'
  post 'product_periods/read_optimization_results', :to => 'product_period_associations#read_optimization_results'
  post 'product_periods/optimize', :to => 'product_period_associations#optimize'
  post 'product_periods/delete_old_plan', :to => 'product_period_associations#delete_old_plan'
  post 'product_periods/show_index_page', :to => 'product_period_associations#show_index_page'

  post 'route_planes/read_and_show_ofv', :to => 'route_plane_associations#read_and_show_ofv'
  post 'route_planes/read_optimization_results', :to => 'route_plane_associations#read_optimization_results'
  post 'route_states/read_and_show_passengers', :to => 'route_state_associations#read_and_show_passengers'
  post 'route_planes/optimize', :to => 'route_plane_associations#optimize'
  post 'route_planes/delete_old_plan', :to => 'route_plane_associations#delete_old_plan'
  post 'route_planes/show_index_page', :to => 'route_plane_associations#show_index_page'

end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_many :products
  has_many :periods, through: :machine_period_associations
  has_many :machine_period_associations, :dependent => :destroy
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]

  # GET /machines
  # GET /machines.json
  def index
    @machines = Machine.all
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
  end

  # POST /machines
  # POST /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1
  # PATCH/PUT /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to machines_url, notice: 'Machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_params
      params.require(:machine).permit(:name, :overtime_cost)
    end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= form_for(@machine) do |f| %>
  <% if @machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
      <% @machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :overtime_cost %><br>
    <%= f.text_field :overtime_cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/machines/edit.html.erb
<h1>Editing Machine</h1>

<%= render 'form' %>

<%= link_to 'Show', @machine %> |
<%= link_to 'Back', machines_path %>

app/views/machines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Machines</h1>

<table id="machines" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Overtime cost</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= machine.name %></td>
        <td><%= machine.overtime_cost %></td>
        <td><%= link_to 'Show', machine %></td>
        <td><%= link_to 'Edit', edit_machine_path(machine) %></td>
        <td><%= link_to 'Destroy', machine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Machine', new_machine_path %>
<br>  <br>
<%= link_to 'Zurück zur Losgrößenplanung', mlclsp_start_path %>

app/views/machines/new.html.erb
<h1>New Machine</h1>

<%= render 'form' %>

<%= link_to 'Back', machines_path %>

app/views/machines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @machine.name %>
</p>

<p>
  <strong>Overtime cost:</strong>
  <%= @machine.overtime_cost %>
</p>

<%= link_to 'Edit', edit_machine_path(@machine) %> |
<%= link_to 'Back', machines_path %>